# Generated by Django 4.0.4 on 2022-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snackmodel',
            old_name='reviewer',
            new_name='purchaser',
        ),
        migrations.RemoveField(
            model_name='snackmodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='snackmodel',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='snackmodel',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
